import type { Metadata } from "next";
import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";

const diabloHeavy = localFont({
  src: "./fonts/DiabloHeavy.ttf",
  variable: "--font-diablo-heavy",
});

const diabloLight = localFont({
  src: "./fonts/DiabloLight.ttf",
  variable: "--font-diablo-light",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${diabloHeavy.variable} ${diabloLight.variable} antialiased dark`}
      >
        <Image src="/background.webp" alt="background" fill className="absolute inset-0 -z-10 object-cover object-right opacity-5" />
        {children}
      </body>
    </html>
  );
}
